modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/JamieBrassel/Lightning-Tweaks/issues"

[[mods]]
modId="lightningtweaks"
version="${file.jarVersion}"
displayName="Lightning Tweaks"
displayURL="https://curseforge.com/minecraft/mc-mods/lightning-tweaks"
logoFile="lightningtweaks.png"
authors="Jamie Brassel"
description='''TODO'''